default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: login_development

test:
  <<: *default
  database: api_development

production:
#  <<: *default
  adapter: mysql2
  database: api
